### ISSUE TITLE
Issue related with ArmourHUD resizing 

### ISSUE THREAD

**Issue by ghost** [Polyfrost/EvergreenHUD#13]
### Original reporter & ticket id

iPLeb_, 1131787803789906012

### Category

Gameplay

### Bug description

Users are unable to resize the module Armour HUD as they want

### Steps to reproduce

Mod Config > Mods > ArmourHUD> Click on "Edit HUD" > Try resizing by dragging the blue box appearing in the down right corner

### Anything else?

https://www.youtube.com/watch?v=qrdpTovZMEg

**Comment by Wyvest** [comment]
fixed by https://github.com/Polyfrost/EvergreenHUD/commit/f0c51060402e1256be02d863fd7857f5e098d99c
