### ISSUE TITLE
Clicks per second does not show

### ISSUE THREAD

**Issue by leofleeo** [Polyfrost/EvergreenHUD#4]
If you enable clicks per second it does not show up on the screen.
I made sure it was not behind the OneConfig GUI.
I am using OneConfig bootstrap
![2023-04-11_16 39 06](https://user-images.githubusercontent.com/83542885/231282839-80de0f61-afae-4b34-a158-ee63c06d8840.png)

**Comment by Wyvest** [comment]
> If you enable clicks per second it does not show up on the screen.
> I made sure it was not behind the OneConfig GUI.
> I am using OneConfig bootstrap
> ![2023-04-11_16 39 06](https://user-images.githubusercontent.com/83542885/231282839-80de0f61-afae-4b34-a158-ee63c06d8840.png)

Is it enabled inside CPS' settings?

**Comment by leofleeo** [comment]
Yes

**Comment by qtdyn** [comment]
Can you try and see if its not positioned offscreen? Try and delete the configuration files in `.minecraft/OneConfig`

**Comment by leofleeo** [comment]
It works now for some reason

**Comment by leofleeo** [comment]
I didn't change anything
