### ISSUE TITLE
Add PotionHUD

### ISSUE THREAD

**Issue by TheTrashCrafter** [Polyfrost/EvergreenHUD#8]
Add a HUD that displays your current Potion Effects, like for example: https://github.com/bspkrs/StatusEffectHUD

**Comment by Mixces** [comment]
A hud that displays your current Potion Effects already exists using OneConfig. [Tellinq's Potion-Effects Display](https://github.com/Tellinq/Potion-Effects)

**Comment by pauliesnug** [comment]
Closed, please leave this in the suggestions channel of the Polyfrost [discord](https://polyfrost.org/discord) or see the link @Mixces posted above.
